### ISSUE TITLE
GitHub Actions: Update package and Node.js versions

### ISSUE THREAD

**Issue by kenzauros** [mseninc/blog#318]
- [blog/.github/workflows at release · mseninc/blog](https://github.com/mseninc/blog/tree/release/.github/workflows)

### TODO

- update older packages (used in `uses` like `actions/github-script@v6`)
- update Node.js versions (used in `actions/setup-node` like `node-version: 18`)

**Comment by jluis9796** [comment]
`uses` packages
 | current | latest |
 | --- | --- |
 |  actions/checkout@v3 |  v4.1.4 |
 | actions/cache@v3 |  v4.0.2 |
 | actions/setup-node@v3 | v4.0.2
 | chetan/invalidate-cloudfront-action@master | v2.4
 | github-script@v6 | v7.0.1
 | reviewdog/action-setup@v1 | v1.3.0
 | 8398a7/action-slack@v3 | v3.16.2

`actions/setup-node` packages
 | current | newer |
 | --- | --- |
 | actions/setup-node@v3 | actions/setup-node@v4 |
 | node-version: 18 |
